CREATE DATABASE IF NOT EXISTS cs633fp;
USE cs633fp;
DROP TABLE IF EXISTS cs633fp.user;

CREATE TABLE IF NOT EXISTS user(
  userID INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) UNIQUE,
  password VARCHAR(100),
  city VARCHAR(100),
  state VARCHAR(100),
  DOB VARCHAR(100)
)ENGINE = innodb;